require 'user.options'
require 'user.mappings'
require 'user.plugins'
require 'user.colorscheme'

require 'user.bufferline'
require 'user.luasnip'
require 'user.indentline'
require 'user.lsp'
require 'user.lualine'
require 'user.terminal'
require 'user.treesitter'
require 'user.cmp'
