hs.hotkey.bind({ "alt", "ctrl" }, "h", WinManager.moveLeft)
hs.hotkey.bind({ "alt", "ctrl" }, "l", WinManager.moveRight)
hs.hotkey.bind({ "alt" }, "a", WinManager.moveFull)
hs.hotkey.bind({ "alt" }, "c", WinManager.moveCenter)
hs.hotkey.bind({ "alt" }, "q", WinManager.arrangeMode)
hs.hotkey.bind({ "alt" }, "w", WinManager.switchWindow)
hs.hotkey.bind({ "alt" }, "d", WinManager.selectDisplay)
hs.hotkey.bind({ "alt" }, "m", WinManager.adjustWindow)
hs.hotkey.bind({ "cmd", "ctrl" }, "f", WinManager.toggleFullScreen)
--
hs.hotkey.bind({ "alt" }, "E", WinManager.focusApplication "com.mitchellh.ghostty")
hs.hotkey.bind({ "alt" }, "F", WinManager.focusApplication "app.zen-browser.zen")
hs.hotkey.bind({ "alt" }, "O", WinManager.focusApplication "com.tinyspeck.slackmacgap")
