env:
    TERM: xterm-256color

# set login shell
shell:
  program: /usr/local/bin/zsh
  args:
    - --login

window:
  dimensions:
    columns: 270
    lines: 60
  padding:
    x: 2
    y: 2
  decorations: false
  scale_with_dpi: true
font:
  normal:
    family: Monaco
    style: Regular
  bold:
    family: Monaco
    style: Bold
  size: 12.0

# gruvbox scheme
custom_cursor_colors: true
colors:
  primary:
    foreground: '0xd5c4a1'
    background: '0x282828'
  cursor:
    cursor: '0xd5c4a1'
    text:   '0x282828'
  normal:
    black:   '0x282828'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xc5c4a1'
  bright:
    black:   '0x665c54'
    red:     '0xfb3934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

# Style of the cursor
# - Block
# - Underline
# - Beam
cursor_style: Block

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

dynamic_title: true

key_bindings:
  - { key: Paste,                    action: Paste            }
  - { key: Copy,                     action: Copy             }
  - { key: V,         mods: Command, action: Paste            }
  - { key: C,         mods: Command, action: Copy             }
  - { key: Q,         mods: Command, action: Quit             }
  - { key: W,         mods: Command, action: Quit             }
  - { key: Key0,      mods: Command, action: ResetFontSize    }
  - { key: Equals,    mods: Command, action: IncreaseFontSize }
  - { key: Plus,      mods: Command, action: IncreaseFontSize }
  - { key: Minus,     mods: Command, action: DecreaseFontSize }
  - { key: Up,                       chars:  "\x1b[A"         }
  - { key: Down,                     chars:  "\x1b[B"         }
  - { key: Right,                    chars:  "\x1b[C"         }
  - { key: Left,                     chars:  "\x1b[D"         }
  - { key: Key2,      mods: Control, chars:  "\x00"           }
  - { key: A,         mods: Control, chars:  "\x01"           }
  - { key: B,         mods: Control, chars:  "\x02"           }
  - { key: C,         mods: Control, chars:  "\x03"           }
  - { key: D,         mods: Control, chars:  "\x04"           }
  - { key: E,         mods: Control, chars:  "\x05"           }
  - { key: F,         mods: Control, chars:  "\x06"           }
  - { key: G,         mods: Control, chars:  "\x07"           }
  - { key: H,         mods: Control, chars:  "\x08"           }
  - { key: I,         mods: Control, chars:  "\x09"           }
  - { key: J,         mods: Control, chars:  "\x0A"           }
  - { key: K,         mods: Control, chars:  "\x0B"           }
  - { key: L,         mods: Control, chars:  "\x0C"           }
  - { key: M,         mods: Control, chars:  "\x0D"           }
  - { key: N,         mods: Control, chars:  "\x0E"           }
  - { key: O,         mods: Control, chars:  "\x0F"           }
  - { key: P,         mods: Control, chars:  "\x10"           }
  - { key: Q,         mods: Control, chars:  "\x11"           }
  - { key: R,         mods: Control, chars:  "\x12"           }
  - { key: S,         mods: Control, chars:  "\x13"           }
  - { key: T,         mods: Control, chars:  "\x14"           }
  - { key: U,         mods: Control, chars:  "\x15"           }
  - { key: V,         mods: Control, chars:  "\x16"           }
  - { key: W,         mods: Control, chars:  "\x17"           }
  - { key: X,         mods: Control, chars:  "\x18"           }
  - { key: Y,         mods: Control, chars:  "\x19"           }
  - { key: Z,         mods: Control, chars:  "\x1A"           }
  - { key: LBracket,  mods: Control, chars:  "\x1B"           }
  - { key: Slash,     mods: Control, chars:  "\x1C"           }
  - { key: RBracket,  mods: Control, chars:  "\x1D"           }
  - { key: Caret,     mods: Control, chars:  "\x1E"           }
  - { key: Underline, mods: Control, chars:  "\x1F"           }
# xterm config
  - { key: Minus,     mods: Control, chars:  "\x1F"           }
  - { key: Key3,      mods: Control, chars:  "\x1B"           }
  - { key: Key4,      mods: Control, chars:  "\x1C"           }
  - { key: Key5,      mods: Control, chars:  "\x1D"           }
  - { key: Key6,      mods: Control, chars:  "\x1E"           }
  - { key: Key7,      mods: Control, chars:  "\x1F"           }
  - { key: Key8,      mods: Control, chars:  "\x7F"           }
