[files]
extend-exclude = [
  ".git/",
  ".direnv/",
  ".pnpm-store/",
  "node_modules/",
  ".oxlintrc.json",
]
ignore-hidden = false

[default.extend-words]
Canva = "Canva"
iterm = "iterm"
noice = "noice"
thm = "thm"
