[tools]
# languages
deno = '1.39'
flutter = 'latest'
golang = '1.21'
java = 'adoptopenjdk-17'
kotlin = '1.9.10'
lua = '5.4'
nodejs = ['18', '20']
python = ['3.10', '3.11', '3.12']
ruby = '3.2'
rust = '1.74'
scala = '3.3'

# development tools
chezmoi = 'latest'
direnv = 'latest'
exa = 'latest'
fzf = 'latest'
ghq = 'latest'
github-cli = 'latest'
jq = 'latest'
lazygit = 'latest'
ripgrep = 'latest'
shellcheck = 'latest'
starship = 'latest'
tmux = 'latest'
zellij = 'latest'
zoxide = 'latest'

duckdb = '0.9'
neovim = '0.9'
terraform = '1.6'

# cloud
awscli = '2'
aws-vault = '7.2'
aws-sam-cli = '1'
gcloud = 'latest'

[plugins]
duckdb = 'https://github.com/asdf-community/asdf-duckdb'

[settings]
legacy_version_file = true
jobs = 2
experimental = true
trusted_config_paths = [
  '~/.config/rtx',
]
