[".config/zsh/plugins/antidote"]
type = "archive"
url = "https://github.com/mattmc3/antidote/archive/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
