tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"

cask "java"

brew "clang-format"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl"
brew "diffutils"
brew "exa"
brew "fzf"
brew "gcc"
brew "gibo"
brew "git"
brew "go"
brew "openssl"
brew "python3"
brew "grc"
brew "grep"
brew "htop"
brew "jp2a"
brew "jq"
brew "mas"
brew "mysql"
brew "nkf"
brew "openconnect"
brew "reattach-to-user-namespace"
brew "ruby"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim", args: ["with-python3"]
brew "w3m"
brew "watch"
brew "wget"
brew "yarn", args: ["without-node"]
brew "zplug"
brew "zsh", args: ["without-etcdir"]

cask "alfred"
cask "dash"
cask "google-chrome"
cask "intellij-idea"
cask "karabiner-elements"
cask "macvim"
cask "spectacle"
cask "visual-studio-code"

mas "Affinity Designer", id: 824171161
mas "Apple Configurator 2", id: 1037126344
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
