tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
brew "curl"
brew "fzf"
brew "git"
brew "go"
brew "jq"
brew "mas"
brew "openconnect"
brew "peco"
brew "python3"
brew "reattach-to-user-namespace"
brew "ruby"
brew "tig"
brew "tmux"
brew "vim", args: ["with-gettext", "with-override-system-vi", "with-lua", "with-python3"]
brew "watch"
brew "wget"
brew "zplug"
brew "zsh", args: ["without-etcdir"]
mas "Affinity Designer", id: 824171161
mas "Apple Configurator 2", id: 1037126344
mas "Controllers Lite", id: 673660806
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
