add_newline = false
scan_timeout = 10
command_timeout = 100

format = "$status$directory$all$fill$cmd_duration$git_branch$git_status$git_state$git_metrics$line_break$character"

[fill]
symbol = '-'
disabled = false

[directory]
format = "[$path]($style) $read_only"

[cmd_duration]
format = "[$duration]($style) "
show_milliseconds = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status $ahead_behind]($style))'

[git_metrics]
disabled = false

[character]
vicmd_symbol = "[N](green)"

[status]
disabled = false
symbol = "status="

[time]
disabled = true

[aws]
disabled = false
format = " [$profile]($style)"
force_display = true

[gcloud]
disabled = false
format = " [$profile]($style)"

[[battery.display]]
threshold = 20

[vagrant]
disabled = true

#############
# languages #
#############

[package]
disabled = true

[kotlin]
format = "[${symbol}=${version}]($style) "
symbol = "kotlin"

[golang]
format = "[${symbol}=${version}]($style) "
symbol = "go"

[java]
format = "[${symbol}=${version}]($style) "
version_format = "v${major}"
symbol = "java"

[nodejs]
format = "[${symbol}=${version}]($style) "
symbol = "node"

[php]
format = "[${symbol}${version}]($style) "
symbol = "php"

[python]
format = "[${symbol}=${version}( \\(${virtualenv}\\))]($style) "
symbol = "py"

[scala]
disabled = true

[terraform]
format = "[${symbol}=${version}\\($workspace\\)]($style)"
symbol = "tf"
