"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
scan_timeout = 10
command_timeout = 500 # ms

format = """\
$directory\
$localip\
$python\
$nodejs\
$terraform\
$line_break\
$character\
"""

right_format = """\
$git_branch\
$git_commit\
$git_metrics\
$memory_usage\
$battery\
$time\
$cmd_duration\
"""


# basic
[fill]
symbol = "-"
disabled = false

[directory]
truncation_length = 5
truncation_symbol = "*"

[localip]
ssh_only = true
disabled = false

[status]
disabled = false
symbol = "status="

[memory_usage]
format = "[mem=$ram_pct]($style) "
disabled = false

[time]
format = "[$time]($style) "
time_format = "%R"
disabled = false

[cmd_duration]
format = "[$duration]($style) "
min_time = 1000
show_milliseconds = false

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""

[git_status]
disabled = true

[git_metrics]
disabled = false

[character]
vimcmd_symbol = "[E](green)"

# language
[package]
disabled = true

[nodejs]
symbol = "js"
format = "([$symbol=${version}]($style) )"
version_format = "${major}.${minor}"

[python]
symbol = "py"
format = "([$symbol=${version}]($style) )"
version_format = "${major}.${minor}"

[terraform]
symbol = "tf"
format = "([$symbol=${version}]($style) )"
version_format = "${major}.${minor}"

# cloud
[aws]
disabled = true
[gcloud]
disabled = true
