#!/bin/sh

help() {
    echo help
}

install_plugin() {
  case $1 in
    pipenv)
      asdf plugin add $plugin https://github.com/amrox/asdf-pyapp.git ;;
    poetry)
      asdf plugin add $plugin https://github.com/asdf-community/asdf-poetry.git ;;
    *)
      asdf plugin add $plugin ;;
  esac
}

install_plugins() {
    echo asdf plugins installing...
    for plugin in $(awk '!/^#/ {print $1}' $HOME/.tool-versions); do
        if [ ! -d $ASDF_DIR/plugins/$plugin ]; then
            echo Install $plugin plugin...
            install_plugin $plugin
        fi
    done
    echo done
}

install() {
  # pythonが依存で必要になるため先にインストール
  asdf install python
  asdf install
}

case $1 in
  help)
    help ;;
  install_plugins)
    install_plugins ;;
  install)
    install ;;
  *)
    echo No Found Command!
    help
    exit 1
    ;;
esac
