#!/bin/bash
nodejs_lts_version=16

help() {
    echo help
}

install_plugin() {
  case $1 in
    pipenv|thefuck)
      asdf plugin add $plugin https://github.com/amrox/asdf-pyapp.git ;;
    *)
      asdf plugin add $plugin ;;
  esac
}

install_plugins() {
    echo asdf plugins installing...
    for plugin in $(awk '!/^#/ {print $1}' $HOME/.tool-versions); do
        if [ ! -d $ASDF_DIR/plugins/$plugin ]; then
            echo Install $plugin plugin...
            install_plugin $plugin
        fi
    done
    echo done
}

install() {
  # pythonが依存で必要になるため先にインストール
  asdf install python
  asdf install
}

clean_global() {
  IFS=$'\n', plugins=$(awk '!/^#/ {print $0}' $HOME/.tool-versions)
  for plugin_info in ${plugins[@]}; do
    IFS=' ', versions=($plugin_info)
    plugin=${versions[0]}
    if [ ! -d $ASDF_DIR/plugins/$plugin ]; then
      continue
    fi

    echo cleanup $plugin...
    IFS=' ', version_dirs="$ASDF_DIR/installs/$plugin/*"

    local lts=0
    if echo $version_dirs | grep nodejs | grep lts >/dev/null; then
      lts=1
    fi

    for dir in ${version_dirs[@]}; do
      size=$(du -hs $dir | cut -f 1)
      check_version=$(basename $dir)
      local ok=0
      for version in ${versions[@]:1}; do
        if [ $lts -eq 1 ]; then
          if echo $check_version | grep -e "^${nodejs_lts_version}\." >/dev/null; then
            ok=1
            echo -e "\e[90m[SKIP] $check_version (alias by lts) ($size)\e[m"
            break
          fi
        fi
        if [ "$size" = "0" ]; then
          ok=1
          break
        fi
        if [ "$check_version" = "$version" ]; then
          echo -e "\e[90m[SKIP] $check_version ($size)\e[m"
          ok=1
          break
        fi
      done
      if [ $ok -eq 0 ]; then
        echo -e "\e[31m[REMOVED] $check_version ($size)\e[m"
        sudo rm -rf $dir
      fi
    done
    echo
  done
}

case $1 in
  help)
    help ;;
  install-plugins)
    install_plugins ;;
  install)
    install ;;
  clean-global)
    clean_global ;;
  *)
    echo No Found Command!
    help
    exit 1
    ;;
esac
