[tools]
deno = 'latest'
flutter = 'latest'
golang = '1.22'
java = 'adoptopenjdk-21.0.4+7.0.LTS'
kotlin = '2'
lua = '5'
node = ['20', '21']
python = ['3.10', '3.11', '3.12']
ruby = '3.3'
rust = '1'
scala = '3.4'
terraform = ['latest', '1.5']
