[tools]
# languages
deno = 'latest'
flutter = 'latest'
golang = '1.22'
java = 'adoptopenjdk-21'
kotlin = '1.9'
lua = '5.4'
nodejs = ['18', '20']
python = ['3.10', '3.11', '3.12']
ruby = '3.3'
rust = 'latest'
scala = '3.3'

# development tools
chezmoi = 'latest'
direnv = 'latest'
exa = 'latest'
fzf = 'latest'
ghq = 'latest'
github-cli = 'latest'
jq = 'latest'
lazygit = 'latest'
ripgrep = 'latest'
shellcheck = 'latest'
starship = 'latest'
tmux = 'latest'
zellij = 'latest'
zoxide = 'latest'

duckdb = '0.9'
neovim = '0.9'
terraform = '1.6'

# cloud
awscli = '2'
aws-vault = '7.2'
aws-sam-cli = '1'
gcloud = 'latest'

[plugins]
duckdb = 'https://github.com/asdf-community/asdf-duckdb'
