# :scheme: https://mise.jdx.dev/schema/settings.json
legacy_version_file = true

trusted_config_paths = ["~/.config/mise"]

jobs = 2
experimental = true

not_found_auto_install = false

[status]
missing_tools = "never" # schema error!!
