name: CI

on:
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: setup stylua
        run: cargo install stylua

      - name: check
        run: |
          pwd
          ls
