name: CI

on:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache
        id: cache
        uses: actions/cache
        with:
          path: ~/.cargo/bin/

      - name: setup stylua
        run: cargo install stylua

      - name: check
        run: stylua --check .
