name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo $ZSH_NAME $ZSH_VERSION
        shell: zsh {0}

      - name: chezmoi
        working-directory: home
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/
          key: cache

      - name: setup stylua
        run: cargo install stylua

      - name: check
        run: stylua --check .
