name: Lua Format

permissions:
  contents: read

on: [pull_request]

env:
  CLICOLOR: 1

jobs:
  stylua:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: v2.1.0
          args: --check .
